# MONGODB DATA
mongoURI: "mongodb://localhost:27017"
mongoDB: "aurorastory"

# SERVER SETTINGS
gameVersion: 62
channelCount: 1
maxPlayers: 500

# LOGIN SETTINGS
loginServerInterval: 500
rankingInterval: 3600
guestLoginEnabled: false
autoRegisterEnabled: true
picEnabled: false
pinEnabled: false

# WORLD SETTINGS
serverFlag: 0
serverMessage: Welcome to Scania!
eventMessage: Scania!

# EVENT SETTINGS
kerningPQEnabled: true
ludibriumPQEnabled: true
orbisPQEnabled: true
ludibriumMazePQEnabled: true

# WORLD RATES
expRate: 10
mesoRate: 10
dropRate: 10
partyExpRate: 10
partyMesoRate: 10
partyDropRate: 10
bossExpRate: 10  # NOTE: Boss drop rate OVERRIDES common drop rate, for bosses only.
bossMesoRate: 10 # NOTE: Boss drop rate OVERRIDES common drop rate, for bosses only.
bossDropRate: 10 # NOTE: Boss drop rate OVERRIDES common drop rate, for bosses only.
questExpRate: 5  # Multiplier for Exp & Meso gains when completing a quest. Only available when USE_QUEST_RATE is true. Stacks with server Exp & Meso rates.
questMesoRate: 5 # Multiplier for Exp & Meso gains when completing a quest. Only available when USE_QUEST_RATE is true. Stacks with server Exp & Meso rates.
pqExpRate: 10
petExpRate: 5